# NUMPY

In [21]:
import numpy as np

# Create matrix

In [3]:
#create3x3 matrix
print(np.arange(10,19).reshape(3,3))

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [9]:
# Describe a matrix
a = np.array([ np.ones(5), np.ones(5) ])
b = np.array([ np.zeros(5), np.zeros(5) ])
c = np.array([ np.zeros(5), np.zeros(5) ])

r = np.array([a, b, c])
r

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
b = np.concatenate([np.arange(1,8), np.arange(6,0,-1)],axis=0)
b

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])

# Broadcasting

The smaller array is “broadcast” across the larger array so that they have compatible shapes.
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. 
Two dimensions are compatible when

    they are equal, or

    one of them is 1

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

Arrays do not need to have the same number of dimensions. For example, if you have a 256x256x3 array of RGB values, and you want to scale each color in the image by a different value, you can multiply the image by a one-dimensional array with 3 values. Lining up the sizes of the trailing axes of these arrays according to the broadcast rules, shows that they are compatible

In [2]:
array_1 = np.array([0, 1, 2, 3, 4])
array_2 = np.array([5, 10, 15, 20, 25])

array_1 * array_2

array([  0,  10,  30,  60, 100])

In [3]:
np.arange(3) + 5 

array([5, 6, 7])

In [4]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [5]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [6]:
# a 1-d array is added to a 2-d array
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b
#A one dimensional array added to a two dimensional array results in broadcasting if number of 1-d array elements matches the number of 2-d array columns.

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [7]:
# When the trailing dimensions of the arrays are unequal, 
# broadcasting fails because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.
b = np.array([1.0, 2.0, 3.0, 4.0])
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [8]:
#  an outer addition operation of two 1-d arrays
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b
# the newaxis index operator inserts a new axis into a, making it a two-dimensional 4x1 array. Combining the 4x1 array with b, which has shape (3,), yields a 4x3 array.

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

# Shape & Dimension

## Check Shape and Dimension

In [3]:
# SCALAR

# Create a scalar
x = np.array(6)
print("x: ", x)

# A scalar has 0 dimension
print("x ndim: ", x.ndim)

# A scalar has no shape
print("x shape:", x.shape)

x:  6
x ndim:  0
x shape: ()


In [4]:
# VECTOR

# Create a scalar
x = np.array([1, 2, 3, 4])
print("x: ", x)

# A vector has 1 dimension
print("x ndim: ", x.ndim)

# Shape
print("x shape:", x.shape)

x:  [1 2 3 4]
x ndim:  1
x shape: (4,)


In [12]:
# MATRIX (2 dimensional array)

x = np.array([[1,2],
              [3,4],
              [5,6]])

print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)  # (number of row, number of col)
print("x size:", x.size)  # number of elements

print(x.flatten())
print(x.reshape(-1))

x:
 [[1 2]
 [3 4]
 [5 6]]
x ndim:  2
x shape: (3, 2)
x size: 6
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [6]:
# 3D Tensor

x = np.array([
              [[1,1],
               [1,1],
               [1,1]],    
              [[0,0],
               [0,0],
               [0,0]]
              ])

print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)

x:
 [[[1 1]
  [1 1]
  [1 1]]

 [[0 0]
  [0 0]
  [0 0]]]
x ndim:  3
x shape: (2, 3, 2)


## Reshape

The function reshapes a tensor to a different shape while keep the amount of items stay the same. For example, an array with shape of (1,6) can be reshaped into a new array with shape (2,3).

In [7]:
# Original array 
x = np.array([1, 2, 3, 4, 5, 6])
print(x)

[1 2 3 4 5 6]


In [8]:
# Reshape to new shape of (2, 3)
np.reshape(x, (2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# When working with large data, user can specify -1 and numpy will automatically 
# calculate the new shape so that it can fit all the items of the original array.

np.reshape(x, (2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

# Array Manipulation

Similar to a Python list, we can access an item (component) in a Numpy array via its index.

## Integer index

In [10]:
# Can access an item (component) in a Numpy array via its index.
sample_array = ['Monday', 'Tuesday', 'Wednesday']
sample_array[0]

'Monday'

In [ ]:
# Numpy array is mutable.
sample_array[0] = 'Sunday'
sample_array

In [11]:
# Indexing is also applied to matrix and higher-dimensional array.
x = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]]) 
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
# row first column second!
# Slice the area of 7, 8, 11, 12
x[1:3, 2:4]
x[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
# Get the whole second row
x[1, :]

# Get the whole second column
x[:, 1]

# Get the first and last columns
x[:, [0, 3]]

# Get the first and last columns
x[:, [0, 3]]

##  Boolean Index

In [16]:
x
x>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
# Boolean index: Return all the items that satisfy the condition that x>5 
x[x > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [18]:
# Combination --- and ---
x[(x > 5) & (x<10)]

array([6, 7, 8, 9])

In [19]:
# Combination --- or ---
x[(x < 5) | (x>10)]

array([ 1,  2,  3,  4, 11, 12])

Write an expression that gives the same array as b EXCEPT all numbers greater than 5 is changed to 5 and other numbers stay the same.

In [15]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
for i in np.where(b>5):
  b[i] = 5
print(b)

b = np.array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 3, 2, 1])
print(np.where(b>5, 5, b))

[1 2 3 4 5 5 5 5 5 4 3 2 1]
[1 2 3 4 5 5 5 5 5 4 3 2 1]


Given an array c below, write an expression that gives an array of the indices of all non-zero numbers in c.

In [17]:
c = np.array([0, 10, 11, 0, 0, 12, 0, 13, 14])

print(np.where(c!=0)[0])


[1 2 5 7 8]


## Aggregate functions

In [18]:
s = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(s)

# Maximum number for the whole matrix
arr_max = s.max() 
print("Max:", arr_max, sep = "\n")

# Minimum number for the whole matrix
arr_min = s.min()
print("Min:", arr_min, sep = "\n")

# Max element in each column
col_max = s.max(axis=0)
print("Max in each column:", col_max, sep = "\n")

# Min element in each row
row_min = s.min(axis=1)
print("Min in each row:", row_min, sep = "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Max:
9
Min:
1
Max in each column:
[7 8 9]
Min in each row:
[1 4 7]


Return the mean of an array

In [19]:
# Example 1
print('Example 1:')
arr = np.arange(9).reshape(3,3)
print(arr)
print('Mean of arr:', arr.mean())
print('Mean of arr:', np.mean(arr))
print('Mean of arr:', arr.sum()/arr.size)

print('\n','-'*30,'\n')
# Example 2
print('Example 2:')
arr = np.random.random((2,5))
print(arr)
print('Mean of arr:', arr.mean())
print('Mean of arr:', np.mean(arr))
print('Mean of arr:', arr.sum()/arr.size)

Example 1:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Mean of arr: 4.0
Mean of arr: 4.0
Mean of arr: 4.0

 ------------------------------ 

Example 2:
[[0.69088553 0.12284345 0.89460783 0.05170944 0.07951532]
 [0.73639257 0.72124704 0.79967234 0.96306472 0.0355071 ]]
Mean of arr: 0.5095445326119361
Mean of arr: 0.5095445326119361
Mean of arr: 0.5095445326119361


# DataCamp